# https://docs.codecov.io/v4.3.6/docs/ignoring-paths
ignore:
  - "*/test_*.py"     # wildcards accepted
  - "tests/*"         # wildcards accepted
  - heroku_runner.py
  - manage.py
  - delete.py
  - tasks.py
